export const sampleData = {
  hand1: [
    [
      { id: 1, name: "Bulbasaur", type: "grass", base_experience: 64 },
      { id: 4, name: "Charmander", type: "fire", base_experience: 62 },
      { id: 7, name: "Squirtle", type: "water", base_experience: 63 },
      { id: 10, name: "Caterpie", type: "bug", base_experience: 39 },
      { id: 13, name: "Weedle", type: "bug", base_experience: 39 },
      { id: 16, name: "Pidgey", type: "flying", base_experience: 50 },
      { id: 19, name: "Rattata", type: "normal", base_experience: 51 },
      { id: 25, name: "Pikachu", type: "electric", base_experience: 112 },
    ],
    [
      { id: 37, name: "Vulpix", type: "fire", base_experience: 63 },
      { id: 39, name: "Jigglypuff", type: "normal", base_experience: 95 },
      { id: 41, name: "Zubat", type: "poison", base_experience: 49 },
      { id: 43, name: "Oddish", type: "grass", base_experience: 78 },
      { id: 46, name: "Paras", type: "bug", base_experience: 57 },
      { id: 48, name: "Venonat", type: "bug", base_experience: 61 },
      { id: 50, name: "Diglett", type: "ground", base_experience: 53 },
      { id: 52, name: "Meowth", type: "normal", base_experience: 58 },
    ],
    [
      { id: 54, name: "Psyduck", type: "water", base_experience: 64 },
      { id: 56, name: "Mankey", type: "fighting", base_experience: 61 },
      { id: 58, name: "Growlithe", type: "fire", base_experience: 70 },
      { id: 60, name: "Poliwag", type: "water", base_experience: 60 },
      { id: 63, name: "Abra", type: "psychic", base_experience: 62 },
      { id: 66, name: "Machop", type: "fighting", base_experience: 61 },
      { id: 69, name: "Bellsprout", type: "grass", base_experience: 60 },
      { id: 72, name: "Tentacool", type: "water", base_experience: 67 },
    ],
    [
      { id: 74, name: "Geodude", type: "rock", base_experience: 60 },
      { id: 77, name: "Ponyta", type: "fire", base_experience: 82 },
      { id: 79, name: "Slowpoke", type: "water", base_experience: 63 },
      { id: 81, name: "Magnemite", type: "electric", base_experience: 65 },
      { id: 84, name: "Doduo", type: "normal", base_experience: 62 },
      { id: 86, name: "Seel", type: "water", base_experience: 65 },
      { id: 88, name: "Grimer", type: "poison", base_experience: 65 },
      { id: 90, name: "Shellder", type: "water", base_experience: 61 },
    ],
  ],

  hand2: [
    [
      { id: 92, name: "Gastly", type: "ghost", base_experience: 62 },
      { id: 95, name: "Onix", type: "rock", base_experience: 77 },
      { id: 98, name: "Krabby", type: "water", base_experience: 65 },
      { id: 100, name: "Voltorb", type: "electric", base_experience: 66 },
      { id: 102, name: "Exeggcute", type: "grass", base_experience: 65 },
      { id: 104, name: "Cubone", type: "ground", base_experience: 64 },
      { id: 108, name: "Lickitung", type: "normal", base_experience: 77 },
      { id: 111, name: "Rhyhorn", type: "ground", base_experience: 69 },
    ],
    [
      { id: 116, name: "Horsea", type: "water", base_experience: 59 },
      { id: 118, name: "Goldeen", type: "water", base_experience: 64 },
      { id: 120, name: "Staryu", type: "water", base_experience: 68 },
      { id: 123, name: "Scyther", type: "bug", base_experience: 100 },
      { id: 126, name: "Magmar", type: "fire", base_experience: 167 },
      { id: 129, name: "Magikarp", type: "water", base_experience: 40 },
      { id: 132, name: "Ditto", type: "normal", base_experience: 101 },
      { id: 133, name: "Eevee", type: "normal", base_experience: 65 },
    ],
    [
      { id: 138, name: "Omanyte", type: "rock", base_experience: 71 },
      { id: 140, name: "Kabuto", type: "rock", base_experience: 71 },
      { id: 143, name: "Snorlax", type: "normal", base_experience: 189 },
      { id: 147, name: "Dratini", type: "dragon", base_experience: 147 },
      { id: 152, name: "Chikorita", type: "grass", base_experience: 64 },
      { id: 155, name: "Cyndaquil", type: "fire", base_experience: 65 },
      { id: 158, name: "Totodile", type: "water", base_experience: 66 },
      { id: 161, name: "Sentret", type: "normal", base_experience: 43 },
    ],
    [
      { id: 163, name: "Hoothoot", type: "normal", base_experience: 52 },
      { id: 165, name: "Ledyba", type: "bug", base_experience: 53 },
      { id: 167, name: "Spinarak", type: "bug", base_experience: 50 },
      { id: 170, name: "Chinchou", type: "water", base_experience: 66 },
      { id: 172, name: "Pichu", type: "electric", base_experience: 41 },
      { id: 174, name: "Igglybuff", type: "normal", base_experience: 70 },
      { id: 176, name: "Togetic", type: "fairy", base_experience: 114 },
      { id: 179, name: "Mareep", type: "electric", base_experience: 56 },
    ],
  ],
};
